apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-sample
    app.kubernetes.io/part-of: purple-mermaid-app-1
  name: python-sample
  namespace: rorai
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: python-sample
status:
  loadBalancer: {}
